### ISSUE TITLE
trouble running deploy.sh on macOS 

### ISSUE THREAD

**Issue by joostd** [google/OpenSK#11]
## Expected Behavior

./deploy.sh app succeeds without error on macOS

## Actual Behavior

./deploy.sh complains about an illegal -A argument to declare and illegal -- argument to stat

## Steps to Reproduce the Problem

1. run ./deploy.sh app on macOS

## Specifications

- Version: 3d3f3554b38ba4e35e7afa552abe891d4c7bf744
- Platform: macOS 10.15

The stat issue can be solved by installing coreutils (`brew install coreutils`) and changing your PATH:

    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

The bash issue can be solved by using a more recent version of bash (`brew install bash`).

**Comment by jmichelp** [comment]
This issue should be fixed now that PR #40 has been merged.
