### ISSUE TITLE
Can't recognize "User intent" using "Push button" of nRF52840-MDK USB Dongle

### ISSUE THREAD

**Issue by kthrtty** [google/OpenSK#114]
## Expected Behavior

At "registration" and/or "authentication", once user push the button of nRF52840-MDK, browser accept "user intent" for authentication. Then requested process will be done in successfuly.

## Actual Behavior

Windows10 does not recognize user operation putting the button to present "user intent", and authentication request fails due to time-out. It may seems that OpenSK firmware does't recognize pushing dongle's button.

## Steps to Reproduce the Problem

1. Exec ./deploy.py and generate target/*.hex
1. Converting *.hex into "UF2" firmware image by [uf2conv](https://github.com/makerdiary/nrf52840-mdk-usb-dongle)
1. Mount the dongle which has UF2 bootloader DFU mode as mass storage
1. Copy the converted firmware image into mass storage
1. Boot the dongle and confirm VID:PID.
1. Set the dongle as google's security key

## Specifications

- Version: commit 642ee69a9bd6939d4f05c298fcfea101a7dc265a
- Platform: Ubuntu 18.04

**Comment by kaczmarczyck** [comment]
We might need more information. The button touches do not leave the security key, but are processed internally. That means, if the behavior is different for Windows 10, then we acutally do send a response, but it is discarded. Can I ask you to append a debug log?
