### ISSUE TITLE
Clippy fails on `libraries/crypto/ec/int256.rs`

### ISSUE THREAD

**Issue by jmichelp** [google/OpenSK#142]
As part of #122 I was trying to check if clippy could be run now that we moved to a more recent libtock-rs.

We still have a couple of warnings from libtock-rs that are easy to fix if they're not already upstream.

The first blocking errors are encountered on the int256 arithmetic.

The error [suspicious_arithmetic_impl](https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_arithmetic_impl) is reported on:
* https://github.com/google/OpenSK/blob/57bf6235394692a95c5bfcae0970fe62800f305d/libraries/crypto/src/ec/int256.rs#L562
* https://github.com/google/OpenSK/blob/57bf6235394692a95c5bfcae0970fe62800f305d/libraries/crypto/src/ec/int256.rs#L592
* https://github.com/google/OpenSK/blob/57bf6235394692a95c5bfcae0970fe62800f305d/libraries/crypto/src/ec/int256.rs#L612

The error [suspicious_op_assign_impl](https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_op_assign_impl) is reported on
* https://github.com/google/OpenSK/blob/57bf6235394692a95c5bfcae0970fe62800f305d/libraries/crypto/src/ec/int256.rs#L576
* https://github.com/google/OpenSK/blob/57bf6235394692a95c5bfcae0970fe62800f305d/libraries/crypto/src/ec/int256.rs#L627

**Comment by gendx** [comment]
Fixed by #162.
