### ISSUE TITLE
Make sure that the Clippy workflow denies warnings and causes the workflow to fail

### ISSUE THREAD

**Issue by gendx** [google/OpenSK#169]
## Expected Behavior

When Clippy warns against a lint with `-D warnings` in a GitHub workflow, the lint is reported and the workflow fails.

## Actual Behavior

On the pull request page, the Clippy workflow appears as green. One has to manually check the workflow's output log to notice the lint.

This seems related to https://github.com/rust-lang/rust-clippy/issues/5749.

## Steps to Reproduce the Problem

1. Add code that triggers a Clippy warning.
1. Create a pull request with that code.
1. Look at the GitHub workflow checks.

**Comment by kaczmarczyck** [comment]
The script should fail now, and with it the workflow that's running it.
