### ISSUE TITLE
Check formatting of the patched Tock repository

### ISSUE THREAD

**Issue by gendx** [google/OpenSK#174]
We should have a CI pass that checks that our patches on top of Tock are properly formatted. We could run `cargo fmt --check` on `third_party/tock/` after the patches being applied.

One caveat is that we currently have custom `rustfmt.toml`, which `cargo fmt` will used even when invoked in a sub-directory. Therefore our formatting rules are not the same as the "vanilla" rules expected by Tock, and we get plenty of warnings unrelated to our patches.

**Comment by kaczmarczyck** [comment]
Closing this as a unnecessary investment.
