### ISSUE TITLE
Maximum PIN retries

### ISSUE THREAD

**Issue by kaczmarczyck** [google/OpenSK#201]
The FIDO conformance tool requires exactly 8 PIN retries as a maximum value.

CTAP 2.0 reads as:

> Maximum consecutive incorrect PIN attempts: 8

The new specification version says:

> Authenticators must allow no more than 8 retries but may set a lower maximum.

Our maximum value has been 6, and that doesn't seem to be backwards compatible. I'll change the maximum number of retries to 8, and this issue documents this behaviour for future reference.

**Comment by jmichelp** [comment]
Currently blocking #196
