### ISSUE TITLE
Do not rely on submodules to specify the rust toolchain

### ISSUE THREAD

**Issue by ia0** [google/OpenSK#261]
We currently use a symlink to specific the `rust-toolchain` based on what is used by `libtock-rs`. This is problematic for github workflows that don't need to clone the submodules since they would use the stable toolchain instead of nightly (and the same version as libtock).

The current proposal solution is to have a copy of the libtock rust-toolchain file instead of a symlink. The CI check executed when bumping libtock should check that the file is in sync.

Once this is fixed, we should clean-up github workflows that force the toolchain to nightly to workaround this issue (e.g. `.github/workflows/persistent_store_test.yml`).

**Comment by kaczmarczyck** [comment]
With #663, the rust-toolchain will be declared in the base directory.

The comment about workflows is obsolete.
