### ISSUE TITLE
OpenSK does not work properly on Microsoft Edge

### ISSUE THREAD

**Issue by ghost** [google/OpenSK#269]
## Expected Behavior
I can register the OpenSK key on my Google account

## Actual Behavior
When I try to register the OpenSK key on my Google account, it gets stuck on the confirmation page
Here are the logs:
```
two-step-verification?rapt=***:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
two-step-verification?rapt=***:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
two-step-verification?rapt=***:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
two-step-verification?rapt=***:1 Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
```

## Steps to Reproduce the Problem

1. Flash the OpenSK firmware to nRF52840-Dongle
2. Open https://myaccount.google.com/signinoptions/two-step-verification on Microsoft Edge
3. Click "Add security key", and click "Next"
4. Tap the button on the OpenSK key

## Specifications

- Version: latest stable
- Platform: Windows

**Comment by kaczmarczyck** [comment]
Hi, thanks for reporting! May I ask you to help narrow down the problem?

Since your report mentions Microsoft Edge explicitly, have you tried the same process on different browsers?
Can you use OpenSK on [webauthn.io](https://webauthn.io/)? Or use OpenSK generally worked for you previously?

**Comment by ghost** [comment]
I haven't tried it with other browsers when I'm creating this issue, since one of my friends can use it with Google Chrome, I think this issue is only occurring on Microsoft Edge. however, when I downloaded Google Chrome and try it on my own, it also occurs on Google Chrome, which is very strange.
It's working with all sites that will trigger the Chromium popup for confirmation, including GitHub, Microsoft Account, and webauthn.io.

**Comment by kaczmarczyck** [comment]
@jmichelp Can you verify with the latest stable version if OpenSK works on Windows for logging into a Google account?

**Comment by geofli** [comment]
I checked, the following U2F command returns 0x6F00 after pressing button.

000103000000400b100bdc57411add74cbd0e9c236f88ffb2e0b0bf194379a2d99ee795e9993b0a54672b222c4cf95e151ed8d4d3c767a6cc349435943794e884f3d023a8229fd0000

No matter on Windows or Mac, no matter to use Google logon or not, U2F has some issue. You can test https://u2fdemo.appspot.com/ on mac with chrome, same issue.

**Comment by kaczmarczyck** [comment]
Just to double check, since 0x6F00 is an internal internal exception that might hint at a device that is not fully set up. Did you configure a certificate (mandatory for U2F)?

```bash
./tools/configure.py \
    --certificate=crypto_data/opensk_cert.pem \
    --private-key=crypto_data/opensk.key
```

**Comment by geofli** [comment]
I did not perform this step. Will test later.

**Comment by geofli** [comment]
It can work (google account and https://u2fdemo.appspot.com/ ) after provisioning attestation certificate and private key. This should be the reason.
OS: Windows 10 20H2 19042, Edge: Version 88.0.705.56 (Official build) (64-bit) .

**Comment by kaczmarczyck** [comment]
Thanks for checking. I'll keep this open for the issue creator. @facilitytinfoil Please let me know if you narrowed the problem in the meantime.

**Comment by ghost** [comment]
> ```shell
> ./tools/configure.py \
>     --certificate=crypto_data/opensk_cert.pem \
>     --private-key=crypto_data/opensk.key
> ```
How can I use this command? I tried this on normal and bootloader mode and I still unable to register my key on Google accounts.
Here is the logs:
```
info: Private key is valid.
info: Certificate is valid.
0it [00:00, ?it/s]
```

**Comment by kaczmarczyck** [comment]
This looks like your device does not enumerate. That explains why it does not work, it is not visible. Have you followed this step?

> On Linux, you may want to avoid the need for `root` privileges to interact with the key. For that purpose we provide a udev rule file that can be installed with the following command:

    ```shell
    sudo cp rules.d/55-opensk.rules /etc/udev/rules.d/ &&
    sudo udevadm control --reload
    ```

Could you check (or paste) the output of `lsusb` (assuming you are on a Linux machine)?

**Comment by ghost** [comment]
Result of lsusb:
```
......
```
I have done that, and I even rebooted my machine, however it still shows this `0it [00:00, ?it/s]` and do nothing.
but when I try to run this command with sudo, I got the following error:
```
info: Private key is valid.
info: Certificate is valid.
Traceback (most recent call last):
  File "./tools/configure.py", line 206, in <module>
    main(parser.parse_args())
  File "./tools/configure.py", line 135, in main
    for authenticator in tqdm(get_opensk_devices(args.batch)):
  File "./tools/configure.py", line 67, in get_opensk_devices
    if (dev.descriptor["vendor_id"],
TypeError: tuple indices must be integers or slices, not str
```

**Comment by kaczmarczyck** [comment]
Since your device worked on your friend's computer, but not your own, I assume the problem is on HID level. Can you check the output of
```shell
ls -l /dev
```

and look out for entries like `hidraw*`? What are read/write permissions, owner and group?

**Comment by ghost** [comment]
after changing the ownership of `/dev/hidraw0` to my own account, I got the same error just like when I'm run this command with sudo, what should I do next?

**Comment by kaczmarczyck** [comment]
You usually don't have to do that, I was just trying to get to the bottom of this. It's hard to guess and fix the problem remotely :) Even more so if your OpenSK works on different computers, meaning the problem is not with our firmware.

**Comment by ghost** [comment]
I fixed that script and now my opensk is working, I don't know if that's beacuse of the version of my fido package is different than yours.

and here is the patch:

```py3
--- configure.py        1970-01-01 00:00:00 0000
+++ configure.py.new    1970-01-01 00:00:00 0000
@@ -64,8 +64,8 @@
 def get_opensk_devices(batch_mode):
   devices = []
   for dev in hid.CtapHidDevice.list_devices():
-    if (dev.descriptor["vendor_id"],
-        dev.descriptor["product_id"]) == OPENSK_VID_PID:
+    if (dev.descriptor[1],
+        dev.descriptor[2]) == OPENSK_VID_PID:
       if dev.capabilities & hid.CAPABILITY.CBOR:
         if batch_mode:
           devices.append(ctap2.CTAP2(dev))
@@ -140,7 +140,7 @@
     aaguid = uuid.UUID(bytes=authenticator.get_info().aaguid)
     info(("Programming device {} AAGUID {} ({}). "
           "Please touch the device to confirm...").format(
-              authenticator.device.descriptor.get("product_string", "Unknown"),
+              "OpenSK",
               aaguid, authenticator.device))
     try:
       result = authenticator.send_cbor(

```

**Comment by kaczmarczyck** [comment]
Thanks for the info.
@jmichelp Maybe interesting for you?

**Comment by jmichelp** [comment]
Interesting. Thanks for letting us know.
Could you please tell us which version of the fido2 python package you're using (`pip3 list | grep fido2` should do the job) as well as the operating system you're using to run the python configuration tool? That would greatly help identifying the issue and ensure that our tool works for everyone.

**Comment by jmichelp** [comment]
Identified the issue.
Newer versions of `fido2` python package moved from `dict` to `NamedTuple` for the descriptor. I'll update the code.
