### ISSUE TITLE
Is nRF52840-PDK supported?

### ISSUE THREAD

**Issue by solder-soldier** [google/OpenSK#32]
Hello,

I flashed my 52840-Preview DK (v0.9.0) with app and os, but OpenSK will not work.
My actions so far:
- disconnecting debug USB
- connecting to device USB port
- after 3-4s LED1 starts kind of double-flashing (boot-loop?)
- pressing boot/reset and any other button

The PDK does not appear as any device (I tried ubuntu and win10).
Are there any other steps after flashing?

Thanks for this project!

**Comment by jmichelp** [comment]
We don't have a PDK board to test. So by default, you can assume it's unsupported until someone makes the effort of testing and eventually add support for it.

It seems, after having a quick look that the datasheet, that the buttons and LEDs are wired the same. So my guess would be that the PDK is using an older revision of the chip (revA or revB) that we don't support for the USB stack.
