### ISSUE TITLE
Bluethooth support?

### ISSUE THREAD

**Issue by jans23** [google/OpenSK#34]
Hi! As far as I see Bluetooth is not (yet?) supported by the firmware. Are there plans to implement Bluetooth support in the firmware?

**Comment by jmichelp** [comment]
You're correct: at the moment only USB transport is supported.

Although there's already some Bluetooth LE support in Tock, as far as I can tell, the support is only partial. At least the security manager (the part responsible for implementing pairing mechanism and link encryption) doesn't seem to be implemented and is mandatory for FIDO.

At the moment we don't know if we will add support for it.
