### ISSUE TITLE
Content are not match or out to date

### ISSUE THREAD

**Issue by ball-spongebob** [google/OpenSK#346]
Please review, edit or update [install.md](https://github.com/google/OpenSK/blob/stable/docs/install.md) and [readme](https://github.com/google/OpenSK/blob/stable/README.md) content is not match or not update in path sector "OpenSK" (compatible devices)

**Comment by kaczmarczyck** [comment]
Hi, thanks for reaching out. Can you provide more details on where you think the documentation is lacking or out of date? What branch are you on?

**Comment by ball-spongebob** [comment]
![20210802_202641](https://user-images.githubusercontent.com/82494278/127871820-80b8cdd8-1bb1-4765-b884-f8bea55f49f4.png)
![20210802_203734](https://user-images.githubusercontent.com/82494278/127871842-c281bbeb-6564-425e-afce-03a0fb319a91.png)
P.S.Why do you care "Branch"?! It so Stupid! Fool! idiot!🙄
