### ISSUE TITLE
Lack of information in the Makerdiary guide, it is not straight forward 

### ISSUE THREAD

**Issue by epita-cs2** [google/OpenSK#349]
## Expected Behavior
We would like to add our github repository for Makerdiary, that we feel it is straight forward and include all the needed information for the users.

## Actual Behavior
OpenSK repository work for Makerdiary usb dongle but we have to get the python code from Makerdiary repository. And their guide it is not straight forward and lacks information. 

## Steps to Reproduce the Problem

1. if possible to add our Github installation guide. https://github.com/epita-cs2/Implementation-OpenSK-on-Makerdiary-nrf52840-mdk-usb-dongle 
1. 
1.

## Specifications

- Version:
- Platform:

**Comment by kaczmarczyck** [comment]
Due to inactivity on #347, I integrated some improvements into our documentation update. Thanks for pointing out the flaws!
