### ISSUE TITLE
OpenSk can be installed on a USB drive?

### ISSUE THREAD

**Issue by sobujbd** [google/OpenSK#36]
### If so, please tell us the possible way. If not, is there any hope so...

**Comment by gregvinyard** [comment]
If you're talking about a regular flash drive, like you'd stick in your computer and store files on, then definitely no.
You need a device that runs the OpenSK application.  It's like a little computer.  It has some storage, but also a CPU, an operating system (Tock OS in this case), buttons to control application functions, etc.
