### ISSUE TITLE
Trouble installing package using a virtual environment

### ISSUE THREAD

**Issue by mlubej** [google/OpenSK#396]
Hi! 

I am experiencing the issue described above

## Expected Behavior

After I recursively download the repo I would expect that running `./setup` would run successfully

## Actual Behavior

I get a crash relatively soon on, stating that `Can not perform a '-- user install, user site packages are not visible in this virtualenv?`

I once was able to achieve installing this, but I have no idea what I did differently, so I can't say much about it.

## Steps to Reproduce the Problem

1. I am using `pyenv` and a virtual environment of version `3.8.7`
2. After activating the venv run the `setup.sh` script
3. Observe the crash

## Specifications

- Version: `pyenv 2.2.0`, `python 3.8.7`, `OpenSK stable`
- Platform: macOS Monterey

**Comment by mlubej** [comment]
Nevermind, I simply replaced every occurrence of `pip3 install --user` with `pip install`.

Closing.

**Comment by kaczmarczyck** [comment]
Thanks for still writing the detailed bug report, maybe someone stumbles upon this issue and sees this workaround!
