### ISSUE TITLE
./tools/configure.py silently fails when no devices found

### ISSUE THREAD

**Issue by liamjm** [google/OpenSK#397]
## Expected Behavior
The tool should warn users when no devices are found and preferably also report a non-zero error code.

## Actual Behavior
The only message displayed on the screen in a terse summary from tqdm module which to the familiar user implies nothing was done. Return code is 0.
```
$ ./tools/configure.py --certificate=crypto_data/opensk_cert.pem --private-key=crypto_data/opensk.key
info: Private key is valid.
info: Certificate is valid.
0it [00:00, ?it/s]

$ echo $?
0
```

## Steps to Reproduce the Problem

1.Have a dev board plugged in (but seemingly not working...?)
1. Run command `/tools/configure.py --certificate=crypto_data/opensk_cert.pem --private-key=crypto_data/opensk.key`
1. Command exits successfully without doing anything

## Specifications

- Version: debian
- Platform: linux (should apply to all as this is a python logic issue)

**Comment by kaczmarczyck** [comment]
This problem is fixed on the `develop` branch, including the non-zero error code. Might take some time to land on stable, but seems to work reasonably well before that.
