### ISSUE TITLE
Please update the Installation guide document about the Nordic nRF52840 Dongle no longer need a Segger J-Link JTAG probe

### ISSUE THREAD

**Issue by Lostsite** [google/OpenSK#402]
Based on issue #47 , OpenSK now can directly write through the USB port, so, please remove the [Installation guide] (https://github.com/google/OpenSK/blob/stable/docs/install.md) JTAG probe connection part. 

>Why I don't do this by myself and add the pull request?

>Because I haven't tested the USB port, and don't know if the JTAG probe gives the extra functions or would the USB port always function as expected, so I send out this issue to see if anyone could run a full test and remove the JTAG probe connection part.

**Comment by kaczmarczyck** [comment]
Hi! I have a few ideas about improving our documentation. I'll keep this until then, and thanks for your interest!
