### ISSUE TITLE
Ensure that the deploy script is also covered by Travis runs

### ISSUE THREAD

**Issue by jmichelp** [google/OpenSK#50]
## Expected Behavior

The `deploy.py` script should be covered by Travis CI to catch errors.

This will imply several things:
- add a `--dry-run` parameter to the script to run all the actions except execution of `JLinkExe`
- split compilation and flash operations (also useful to support more flashing methods such as USB bootloader, OpenOCD, etc.)
- assess if `tockloader` also has such a dry-run flag
- modify Travis configuration to run deploy script with the different parameters

## Actual Behavior

Script is not run.

## Steps to Reproduce the Problem

N/A

## Specifications

- Version: N/A
- Platform: N/A

**Comment by jmichelp** [comment]
As suggested during the review of PR #49, we should also:

- Add linter for python and markdown
- Check for proper formatting of python and markdown files

**Comment by gendx** [comment]
The `workflows/boards_build.yml` already tests `./deploy.py --board=<board> --no-app --programmer=none`. I guess the `--programmer=none` corresponds to the `--dry-run` parameter proposed in this issue.

Should we add anything else?
I'd say at the very least not only testing `--no-app`.

**Comment by kaczmarczyck** [comment]
Several `--programmer=none` are added.
