### ISSUE TITLE
User presence touch timeouts get treated as user presence

### ISSUE THREAD

**Issue by liamjm** [google/OpenSK#519]
## Expected Behavior
When waiting for user presence, a timeout should lead to an error, eg CTAP2_ERR_USER_ACTION_TIMEOUT

## Actual Behavior
Successful response is returned to host.

## Steps to Reproduce the Problem

1.  send a AuthenticatorMakeCredential command
1.  don't touch the buttons

## Specifications

- Version: develop branch
- Platform: linux

**Comment by liamjm** [comment]
Issue is caused by the result variable from the presence check being overwritten by the result from sending the keepalive packet:

https://github.com/google/OpenSK/blob/develop/src/ctap/mod.rs#L352-L355

```
result = env.user_presence().wait_with_timeout(...);
if !matches!(result, Err(UserPresenceError::Timeout)) {
   break;
 }   
result = send_keepalive_up_needed(env, channel, KEEPALIVE_DELAY);
if result.is_err() {
  break;
}
```

**Comment by kaczmarczyck** [comment]
I checked on the latest develop. If I wait for touch timeout, it returns `CTAP2_ERR_USER_ACTION_TIMEOUT` as expected. Can be closed?

**Comment by liamjm** [comment]
Yep, SGTM.
