### ISSUE TITLE
Improve continuous integration

### ISSUE THREAD

**Issue by jmichelp** [google/OpenSK#54]
## Expected Behavior

All formatting, tests, and builds are run through Github workflows.

We should also use the [Problem matchers](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md) wherever we can to have more automated actionable content in the Github PR review system.

## Actual Behavior

Continuous integration runs on Travis-CI

## Steps to Reproduce the Problem

N/A

## Specifications

- Version: N/A
- Platform: N/A

**Comment by jmichelp** [comment]
PR #53 started duplicating a few tests from Travis-CI.

**Comment by jmichelp** [comment]
Now with PR #61 we have even better coverage than what Travis was doing, tests run in parallel instead of sequentially.

Leaving the bug open though because we're missing clippy due to libtock which triggers clippy errors. Will revisit when we'll be able to bump libtock-rs version.

Also leaving the travis-ci at the moment to ensure that both are catching errors on upcoming PRs and we can disable it once we're confident that everything runs fine.

**Comment by gendx** [comment]
Travis-CI has been broken in the last pull requests. Is it still useful or should we just get rid of it?

**Comment by jmichelp** [comment]
I removed it. We were only keeping it for a while to see if Github workflows were correctly on par with Travis-CI
