### ISSUE TITLE
Respect `CARGO_TARGET_DIR` env var instead of hardcoding target directory

### ISSUE THREAD

**Issue by L0g4n** [google/OpenSK#563]
## Expected Behavior

I have set the environment variable `CARGO_TARGET_DIR` to a custom directory.
What is `CARGO_TARGET_DIR`: [Reference](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads)

> Location of where to place all generated artifacts, relative to the current working directory. See [build.target-dir](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir) to set via config.

The deploy script should respect the env var and be able to resolve the path.

## Actual Behavior

The deploy script does not respect the env var and assumes the default hardcoded `target` directory, relative to the current working directory. This causes a failing deployment of the firmware.

## Steps to Reproduce the Problem

1. Set `CARGO_TARGET_DIR` to a custom directory, e.g. `CARGO_TARGET_DIR=custom_dir`
1. Run the deploy script and observe the file not found errors

**Comment by kaczmarczyck** [comment]
Fixed via #564
