### ISSUE TITLE
MakeCredentialPinAuthProtocolTest return code mismatch 

### ISSUE THREAD

**Issue by bunnie** [google/OpenSK#582]
## Expected Behavior
This test from the CTAP2 test tool:

https://github.com/google/CTAP2-test-tool/blob/1afd50bd1b700dc86d6dffeca70a331771d24e45/src/tests/make_credential.cc#L503-L515

Should conclude with the correct error code.

## Actual Behavior

It is reporting an incorrect return code mismatch:
```
 Test successful: Tests the response on an empty PIN auth without a PIN in MakeCredential.
 Test successful: Tests if the PIN protocol parameter is checked in MakeCredential.
 Expected error code `CTAP2_ERR_PIN_AUTH_INVALID`, got `CTAP1_ERR_INVALID_PARAMETER`.
```

## Steps to Reproduce the Problem

1. Run the CTAP2-test-tool against an OpenSK implementation on the `develop` branch
1. Search for the error in the log

## Specifications

- Version: `develop` fork
- Platform: Precursor

**Comment by kaczmarczyck** [comment]
Hi, the error code changed between CTAP 2.0 and 2.1. OpenSK is more up to date than the Test Tool. I double checked the specification, and it matches OpenSK:
![inv_param](https://user-images.githubusercontent.com/43844792/217253310-735e812d-5a01-48af-bfc4-3bbad47a7300.png)

Fixing this is part of [this issue on the Test Tool](https://github.com/google/CTAP2-test-tool/issues/16). I propose to close this issue and the corresponding PR?

**Comment by kaczmarczyck** [comment]
One general comment: The error code checks in the Test Tool are currently too strict. The specification shuffled error codes around a bit between 2.0 and 2.1. So even a correctly implemented security key will return wrong error codes, if you compare against the wrong CTAP version.

**Comment by bunnie** [comment]
Yep, sounds good. I had assumed the test tool was the ground truth, but it sounds like the test tool isn't up to date. We can close this out if that's the case.
