### ISSUE TITLE
pip install --user is unnecessary

### ISSUE THREAD

**Issue by micolous** [google/OpenSK#587]
`./setup.sh` and other tools run `pip install --user`.

This is unneeded on current versions of pip, as they will switch automatically:

> Defaulting to user installation because normal site-packages is not writeable

*Additionally*, specifying `--user` breaks in virtualenv (#396), which makes it harder to isolate any special tools or specific library versions that OpenSK wants to use from other Python applications.

**Comment by kaczmarczyck** [comment]
Thanks! I hope a requirements.txt works better for you? In that case, it is fixed.

**Comment by micolous** [comment]
Yeah, `requirements.txt` is much cleaner. Thanks!
