### ISSUE TITLE
versions in develop should include FIDO_2_1

### ISSUE THREAD

**Issue by micolous** [google/OpenSK#589]
`develop` supports features like `authenticatorSelection`, `authnrCfg`, `setMinPINLength`, `credMgmt`, and `pinProtocols = 2` which are all `FIDO_2_1` features.

`stable` [also supports `authenticatorSelection`](https://github.com/google/OpenSK/blob/1b70583243a45392ca6638e891b3bbb965fd9be5/src/ctap/response.rs#L50-L51).

Based on [the public docs](https://fidoalliance.org/specs/fido2/vendor/), the only difference in `FIDO_2_1_PRE` are features not supported by OpenSK: `userVerificationMgmtPreview` / `authenticatorBioEnrollment` (which isn't relevant) and `credMgmtPreview` / `authenticatorCredentialManagement`.

So it is an error for OpenSK to report `FIDO_2_1_PRE`.

This is probably related to https://github.com/google/OpenSK/issues/106

**Comment by kaczmarczyck** [comment]
Thanks for reporting, fixed!
