### ISSUE TITLE
AuthenticatorConfigParameters swaps pinUvAuthProtocol and pinUvAuthParam field IDs

### ISSUE THREAD

**Issue by micolous** [google/OpenSK#593]
AuthenticatorConfigParameters in OpenSK:

https://github.com/google/OpenSK/blob/a2229869956b014dd44f1e6e4924c9d87c32316c/src/ctap/command.rs#L470-L473

[The spec says][0]:

Parameter name | Data type | Required? | Notes
-- | -- | -- | --
subCommand (0x01) | Unsigned Integer | Required | subCommand currently being requested
subCommandParams (0x02) | CBOR Map | Optional | Map of subCommands parameters.
**pinUvAuthProtocol (0x03)** | Unsigned Integer | Optional | PIN/UV protocol version chosen by the platform.
**pinUvAuthParam (0x04)** | Byte String | Optional | First 16 bytes of HMAC-SHA-256 of contents using pinUvAuthToken.

When attempting to configure anything with a `pinUvAuthProtocol` / `pinUvAuthParam` parameter, OpenSK returns "Unexpected Type".

[0]: https://fidoalliance.org/specs/fido-v2.1-ps-20210615/fido-client-to-authenticator-protocol-v2.1-ps-errata-20220621.html#authenticatorConfig

**Comment by kaczmarczyck** [comment]
Nice catch, thanks for reporting.

Can be verified with this Python script:

```
from fido2.ctap2 import ClientPin, Config, PinProtocolV2
import uuid

from tools.configure import error, fatal, get_opensk_devices, info


def main():
  devices = get_opensk_devices(False)
  if not devices:
    fatal("No devices found.")

  for authenticator in devices:
    aaguid = uuid.UUID(bytes=authenticator.get_info().aaguid)
    info(f"Config device AAGUID {aaguid} ({authenticator.device}).")

    pin_protocol = PinProtocolV2()
    client_pin = ClientPin(authenticator, pin_protocol)
    auth_token = client_pin.get_pin_token("1234", ClientPin.PERMISSION.AUTHENTICATOR_CFG)
    config = Config(authenticator, pin_protocol, auth_token)
    info("Toggle AlwaysUV...")
    config.toggle_always_uv()
    info("Toggle back...")
    config.toggle_always_uv()
    info("Done")


if __name__ == "__main__":
  main()
```
