### ISSUE TITLE
How to change pin in Makerdiary nRF52840-MDK USB dongle

### ISSUE THREAD

**Issue by tu6ge** [google/OpenSK#622]
## Specifications

- Version: stable
- Platform: ubuntu 22.04 / nRF52840-MDK USB dongle

**Comment by kaczmarczyck** [comment]
Hi! This is not an OpenSK specific capability, all CTAP2 security keys allow changing the PIN. Platforms should offer a user interface, for example if you use

- Chrome, go to: chrome://settings/securityKeys
- Windows, go to settings and look for Accounts > Sign-in options > Security Key

Did that answer your question?

**Comment by tu6ge** [comment]
Thank you for your guidance. Based on the method you provided, I have successfully made the changes
