### ISSUE TITLE
wrong board type in flashing command in install.md

### ISSUE THREAD

**Issue by iayanpahwa** [google/OpenSK#650]
## Expected Behavior
Board type wrong in install.md

```
If your board is already flashed with Tock OS, you may skip installing it: ./deploy.py --board=nrf52840dk --opensk --no-tockos
```
should be :
```
If your board is already flashed with Tock OS, you may skip installing it: ./deploy.py --board=nrf52840dk_opensk --opensk --no-tockos
```

**Comment by ia0** [comment]
Thanks for the report! But as said in #651, the documentation is actually correct in both the stable and develop branch. The `nrf52840dk_opensk` board is specific to the develop branch and Github shows you the stable branch by default.
