### ISSUE TITLE
Question: what is the purpose of `feature = "vendor_hid"`?

### ISSUE THREAD

**Issue by bradjc** [google/OpenSK#692]
I'm trying to understand 1) the differences between OpenSK and upstream Tock, and 2) the differences between CTAP2.0 and CTAP2.1 in OpenSK. One major difference is the addition of the vendor HID USB interface.

From what I can tell, OpenSK supports the same functionality over both HID interfaces, and the userspace app can be configured to use either. What I'm not sure about is when to use which one, and if the vendor HID interface is meant to be used long-term or is perhaps for debugging/testing. Is there a document or description of the use case for the vendor HID interface?

**Comment by kaczmarczyck** [comment]
The `0xF1D0` usage page can be locked down by a browser or OS. In those cases, it might still be desirable to make the vendor commands accessible to, e.g., a browser extension. To support that use case, we added `vendor_hid`, and this use case also explains the name.

If you interact with OpenSK from a Linux terminal for configuration and from any browser for normal FIDO operation, you don't need `vendor_hid`.

**Comment by bradjc** [comment]
Thanks!
