### ISSUE TITLE
OpenSK source  recover without reset button.

### ISSUE THREAD

**Issue by xaqfan** [google/OpenSK#86]
How can I  recover  dfu mode and reflash  without reset button.
My board is nordic52840 dongle (PCA10059).

I have checked office doc,and find dfu trigger library.
But i not sure the library's name,and source is contains it or not.

- Version:
- Platform:

**Comment by jmichelp** [comment]
I already mentioned this here, that's the 2nd bullet point: https://github.com/google/OpenSK/issues/81#issuecomment-598654588

On the Makerdiary, if I'm correct, maintaining the button pressed while inserting the dongle does the job. I tried many things with the Nordic dongle without any luck so far. I have to look on the source code which button/GPIO they assigned to this feature.

**Comment by tabroughton** [comment]
> I have to look on the source code which button/GPIO they assigned to this feature.

I'm in the same position, I flashed my dongle and didn't succeed but I lost DFU mode.  I've currently got micropython on there which I've flashed with SWD (nucleo).  But I'd like to get my DFU mode back so I can try the new deploy.py you're working on.

Looking at schematic I see RESET is attached to GPIO 0.18, 0.19, 0.21, 0.23 and 0.25 so I'm guessing pulling any of those LOW would trigger DFU mode if using [the nordic DFU trigger library](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v15.0.0%2Flib_dfu_trigger_usb.html)

**Comment by xaqfan** [comment]
But , how to use nordic dfu trigger library in opensk source code ?

**Comment by githubquestions** [comment]
hello basic question - how to know if lost DFU mode in failed flash? Using `/deploy.py --board=nrf52840_dongle_dfu --opensk --programmer=nordicdfu` from @xaqfan fork. Was getting `Couldn't find any DFU device on your system.` Unsure if flash failed and DFU mode lost or if never worked

**Comment by githubquestions** [comment]
hello basic question - how to know if lost DFU mode in failed flash? `Using /deploy.py --board=nrf52840_dongle_dfu --opensk --programmer=nordicdfu` from @xaqfan fork. Was getting Couldn't find any DFU device on your system. Unsure if DFU mode lost or if never worked

update: turns out just needed libusb reinstall. Going to delete because likely off-topic

**Comment by xaqfan** [comment]
> > I have to look on the source code which button/GPIO they assigned to this feature.
> 
> I'm in the same position, I flashed my dongle and didn't succeed but I lost DFU mode. I've currently got micropython on there which I've flashed with SWD (nucleo). But I'd like to get my DFU mode back so I can try the new deploy.py you're working on.
> 
> Looking at schematic I see RESET is attached to GPIO 0.18, 0.19, 0.21, 0.23 and 0.25 so I'm guessing pulling any of those LOW would trigger DFU mode if using [the nordic DFU trigger library](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v15.0.0%2Flib_dfu_trigger_usb.html)

Have you solved this problem？ I have checked nordic office doc some days,and no ideas

**Comment by BigPictures** [comment]
This is a feature of the [Makerdiary / Adafruit bootloader](https://github.com/makerdiary/uf2-bootloader). It claims to work on the Nordic boards as well.

> On the Nordic PCA10059 Dongle board, DFU is connected to the white button. FRST is connected to pin 1.10. Ground it to pull FRST low, as if you had pushed an FRST button. There is an adjacent ground pad.
