### ISSUE TITLE
Dongle only detected when Jlink is connected

### ISSUE THREAD

**Issue by ibndias** [google/OpenSK#88]
## Expected Behavior
NRF52840 Dongle works with/without Jlink is connected.

## Actual Behavior
NRF52840 Dongle only works when Jlink is connected. This is the first time I tried to compile in dongle. Am i missing something here?

## Steps to Reproduce the Problem

1. Clone latest master repo
2. Run `./setup.sh`
3. Run `./deploy.py --board=nrf52840_dongle --opensk --programmer=jlink`

## Specifications

- Version: Latest commit: https://github.com/google/OpenSK/commit/284b1426ecaf71d7a9b2e1b445ed55953efbd370
- Platform: Linux Elementary OS, Jlink Pro

**Comment by jmichelp** [comment]
I'm not sure I fully understand what's happening.

If you set the programmer to be JLink, then yes, the script will indeed expect a JLink programer to be hooked to the dongle in order to flash it. But once flashed you don't need the JLink programer to use the dongle (unless if you want to flash it again).

**Comment by superderon** [comment]
> I'm not sure I fully understand what's happening.
> 
> If you set the programmer to be JLink, then yes, the script will indeed expect a JLink programer to be hooked to the dongle in order to flash it. But once flashed you don't need the JLink programer to use the dongle (unless if you want to flash it again).

Sorry maybe the title is misleading here.
After flashing, I managed to be able to use OpenSK with my dongle, the led flashing when the web request for authentication. Pressing reset blinks the green led. (This is happens with Jlink still connected)

But then i remove the Jlink, the dongle is dead, no more led flashing when the website request for authentication. Pressing reset but nothing happens with the led.

**Comment by superderon** [comment]
Seems like the dongle not detected. When i connect the Jlink, i can run `lsusb` 

and i got `Bus 001 Device 030: ID 1915:521f Nordic Semiconductor ASA `

but when i remove the jlink, its gone

**Comment by ibndias** [comment]
I use another dongle and it works fine, so it's a hardware problem.

**Comment by ibndias** [comment]
Just for information, I found that one of my dongle component is missing, and it's causing my dongle undetected.
![Screenshot from 2020-04-10 17-33-25](https://user-images.githubusercontent.com/3958152/78977802-b48f1780-7b53-11ea-81e0-3bbc82109e4b.png)
Seems like I've pushed the Tag-Connect TC2050 retainer clip too hard while flashing it.
