### ISSUE TITLE
yapf: "chromium" is not a valid style or file path

### ISSUE THREAD

**Issue by gendx** [google/OpenSK#98]
## Expected Behavior

`pylint/yapf` isn't affected by a pull request which doesn't modify any Python file.

## Actual Behavior

This fails on #97.

```
Run echo ::add-matcher::./.github/python_matcher.json
  echo ::add-matcher::./.github/python_matcher.json
  yapf --style=chromium --recursive --exclude third_party --diff .
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.6/x64
yapf: "chromium" is not a valid style or file path
##[error]Process completed with exit code 1.
```

## Steps to Reproduce the Problem

See https://github.com/google/OpenSK/pull/97/checks?check_run_id=614885048

**Comment by jmichelp** [comment]
Seems related to this commit: https://github.com/google/yapf/commit/22ef70f3c497436adf59934b2ffa84ce6f962b88

I have to do some test then. Maybe we'll move to the "google" style then.

**Comment by jmichelp** [comment]
After some test, the provided google style moves to 4 spaces soft tabs. So I picked the yapf style which is now the replacement for the chromium one.
